<ExampleBackdrop>

    MDBackdrop:
        id: backdrop
        on_open: print("on_open")
        on_close: print("on_close")
        left_action_items: [["menu", lambda x: self.open()]]
        title: app.title
        header_text: "Menu:"

        MDBackdropBackLayer:
            BackLayer:
                id: backlayer

        MDBackdropFrontLayer:
            FrontLayer:
                backdrop: backdrop
                backlayer: backlayer
